version: "3"
services:
  db:
    image: mysql:latest
    container_name: mall-mysql
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./data/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123