version: "3"
services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    volumes:
      - ./nacos/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./data/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123