server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_item?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver